#!/usr/bin/env bash

# Stop if we get errors.
set -e

cd $(dirname $0)

npm test || {
    echo
    echo "======================================================================"
    echo "Error: tests failed!"
    exit 1
}

SERVO_DIR=$1
if [[ ! -e "$SERVO_DIR" ]]; then
    echo
    echo "======================================================================"
    echo "Error: bad path to Servo checkout: $SERVO_DIR"
    exit 1
fi

PROFILE_COMPONENT_DIR=$SERVO_DIR/components/profile
if [[ ! -e "$PROFILE_COMPONENT_DIR" ]]; then
    echo
    echo "======================================================================"
    echo "Error: missing components/profile in Servo checkout: $PROFILE_COMPONENT_DIR"
    exit 1
fi

function banner {
    echo "/*"                                                                            > $1
    echo "!!! THIS FILE IS COPIED FROM https://github.com/fitzgen/servo-trace-dump !!!" >> $1
    echo "Make sure to upstream changes, or they will get lost!"                        >> $1
    echo "*/"                                                                           >> $1
}

TRACE_DUMP_JS="$PROFILE_COMPONENT_DIR/trace-dump.js"
banner $TRACE_DUMP_JS
cat trace-dump.js >> $TRACE_DUMP_JS

TRACE_DUMP_CSS="$PROFILE_COMPONENT_DIR/trace-dump.css"
banner $TRACE_DUMP_CSS
cat trace-dump.css >> $TRACE_DUMP_CSS

echo
echo "======================================================================"
echo "OK"
